// Dosya Yolu: src/app/features/page.tsx
import React from 'react';
import Link from 'next/link';
import Navbar from '@/src/components/Navbar';
import {
  ArrowRight, TrendingUp, Target, BarChart4, DollarSign,
  FileDown, Zap, ShieldCheck, Sparkles
} from 'lucide-react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Features — SellfCompete',
  description: 'Every feature inside SellfCompete: marketplace scraping, deep sentiment analysis, market economics, strategic gap detection, and Word-ready exports.',
  openGraph: {
    title: 'SellfCompete Features — What Every Audit Includes',
    description: 'Marketplace scraping, sentiment analysis, market economics, and strategic gaps — all in one audit.',
    url: 'https://www.sellfcompete.com/features',
    siteName: 'SellfCompete',
    type: 'website',
  },
};

const features = [
  {
    icon: TrendingUp,
    title: 'Category Top Sellers',
    desc: 'The 10 products actually dominating your category on Trendyol or Amazon — brand, product name, estimated market share, price, and their key advantage. Not a list of marketplaces; a list of the specific products beating you.',
  },
  {
    icon: Target,
    title: 'Deep Sentiment & Feature Requests',
    desc: 'Reviews read and scored automatically — overall sentiment, top praises, critical pain points, and the single most valuable output: feature requests customers are already asking competitors for.',
  },
  {
    icon: BarChart4,
    title: 'Market Economics',
    desc: 'Category trend direction, estimated annual volume, barrier to entry, and average marketplace commission — the context that turns a product list into a business decision.',
  },
  {
    icon: DollarSign,
    title: 'Strategic Gaps',
    desc: 'Pricing opportunity, product improvement direction, and a marketing angle — generated by cross-referencing marketplace data, web research, and your own uploaded documents.',
  },
  {
    icon: FileDown,
    title: 'Word-Ready Export',
    desc: 'Every audit can be downloaded as a formatted Word document — ready to forward, present, or file, no reformatting required.',
  },
  {
    icon: ShieldCheck,
    title: 'Live Data, Every Time',
    desc: 'No cached snapshots. Every audit runs a fresh scrape and a fresh web research pass at the moment you request it.',
  },
];

export default function FeaturesPage() {
  return (
    <div className="relative bg-[#0a0a0a] text-zinc-100 min-h-screen font-sans selection:bg-orange-500 selection:text-white overflow-hidden">
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute top-[10%] right-[-5%] w-[40%] h-[40%] bg-orange-500/5 rounded-full blur-[120px]"></div>
        <div className="absolute bottom-[20%] left-[-10%] w-[30%] h-[30%] bg-zinc-500/5 rounded-full blur-[100px]"></div>
      </div>

      <Navbar />

      <section className="relative pt-48 pb-24 px-6 max-w-7xl mx-auto">
        <div className="text-center mb-20">
          <p className="text-orange-500 text-[10px] font-black uppercase tracking-[0.3em] mb-4">Features</p>
          <h1 className="text-5xl md:text-7xl font-bold tracking-tighter mb-6 uppercase italic text-white">
            Every Audit, <span className="text-orange-500">Fully Loaded</span>
          </h1>
          <p className="text-zinc-500 text-lg max-w-2xl mx-auto font-medium leading-relaxed">
            One credit gets you all six of these — not a limited free tier with feature-gated add-ons.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-24">
          {features.map((f) => (
            <div key={f.title} className="bg-zinc-900/40 backdrop-blur-xl border border-zinc-800/50 rounded-[2.5rem] p-10 group hover:border-orange-500/20 transition-all duration-500">
              <f.icon className="text-orange-500 mb-6 group-hover:scale-110 transition-transform duration-500" size={32} />
              <h3 className="text-xl font-bold tracking-tight mb-3 text-white">{f.title}</h3>
              <p className="text-zinc-500 text-sm leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>

        {/* IDEA VS LINK — iki giriş modu, gerçek ürün davranışı */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <div className="bg-zinc-900/40 backdrop-blur-xl border border-zinc-800/50 rounded-[2.5rem] p-10">
            <Zap className="text-orange-500 mb-6" size={28} />
            <h3 className="text-xl font-bold tracking-tight mb-3 text-white">Audit a Live Product</h3>
            <p className="text-zinc-500 text-sm leading-relaxed">Paste a Trendyol or Amazon product URL and get a direct, product-specific competitive audit — pulled from that exact listing and its category.</p>
          </div>
          <div className="bg-zinc-900/40 backdrop-blur-xl border border-zinc-800/50 rounded-[2.5rem] p-10">
            <Sparkles className="text-orange-500 mb-6" size={28} />
            <h3 className="text-xl font-bold tracking-tight mb-3 text-white">Audit an Idea</h3>
            <p className="text-zinc-500 text-sm leading-relaxed">No product yet? Describe it in plain text. SellfCompete identifies the right category and finds its real, existing competitors before you build anything.</p>
          </div>
        </div>

        {/* YENİ: E-ticaret yöneticilerine bağlamsal yönlendirme — hem UX hem internal link */}
        <Link
          href="/for-ecommerce"
          className="flex items-center justify-between bg-zinc-900/60 border border-zinc-800 hover:border-orange-500/30 rounded-[2rem] p-8 mb-24 transition-all group"
        >
          <div>
            <p className="text-[10px] font-black uppercase tracking-widest text-orange-500 mb-2">Running a Store?</p>
            <h3 className="text-lg font-bold text-white">See what SellfCompete looks like for e-commerce managers</h3>
          </div>
          <ArrowRight className="text-zinc-600 group-hover:text-orange-500 group-hover:translate-x-1 transition-all shrink-0" size={24} />
        </Link>

        {/* CTA */}
        <div className="text-center bg-gradient-to-br from-orange-500/10 to-transparent border border-orange-500/20 rounded-[2.5rem] p-16">
          <h2 className="text-3xl md:text-5xl font-black tracking-tighter uppercase italic text-white mb-6">
            See It on Your <span className="text-orange-500">Own Product</span>
          </h2>
          <p className="text-zinc-500 text-base max-w-xl mx-auto mb-10">
            3 free audits, 7 days, no credit card required.
          </p>
          <Link href="/trial-signup" className="inline-flex bg-orange-500 text-black px-10 py-5 rounded-full font-black uppercase italic tracking-tight hover:bg-orange-400 transition-all items-center gap-2 group shadow-xl shadow-orange-500/20">
            Start Free Trial <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" />
          </Link>
        </div>
      </section>
    </div>
  );
}